# Generated by Django 5.2.12 on 2026-04-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiel',
            name='cidade',
            field=models.CharField(blank=True, default='Itaquiraí', max_length=100, verbose_name='Cidade'),
        ),
    ]
