# Generated by Django 5.2.12 on 2026-04-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fieis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_pagamento', models.DateField(verbose_name='Data de pagamento')),
                ('referencia', models.DateField(verbose_name='Referência (mês/ano)')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO', 'Cartão')], default='DINHEIRO', max_length=20, verbose_name='Forma de pagamento')),
                ('pago', models.BooleanField(default=True, verbose_name='Pago')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('fiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dizimos', to='fieis.fiel', verbose_name='Fiel')),
            ],
            options={
                'verbose_name': 'Dízimo',
                'verbose_name_plural': 'Dízimos',
                'ordering': ['-data_pagamento', '-criado_em'],
            },
        ),
    ]
